/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.start;

import frontend.Components.Clock;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hagras
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        setUndecorated(true);
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frontend.Components.Button button1 = new frontend.Components.Button();
        clock1 = new frontend.Components.Clock();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        MainSide = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        StockManagement = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        Approval = new javax.swing.JLabel();
        Trading = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Obj = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        tfirst = new javax.swing.JTextField();
        tlast = new javax.swing.JTextField();
        tusername = new javax.swing.JTextField();
        tpassword = new javax.swing.JTextField();
        button2 = new frontend.start.Button();
        button3 = new frontend.start.Button();
        button4 = new frontend.start.Button();
        jScrollPane5 = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        button5 = new frontend.start.Button();
        button6 = new frontend.start.Button();
        button7 = new frontend.start.Button();
        jScrollPane6 = new javax.swing.JScrollPane();
        stocktable = new javax.swing.JTable();
        tprofit = new javax.swing.JTextField();
        tdividend = new javax.swing.JTextField();
        tinitial = new javax.swing.JTextField();
        tquantity = new javax.swing.JTextField();
        tcompany = new javax.swing.JTextField();
        ttrading = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Stocks = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Pricehistory = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        ApprovalSys = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        TradingSys = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));

        MainSide.setBackground(new java.awt.Color(0, 143, 255));

        jPanel3.setBackground(new java.awt.Color(0, 118, 255));

        Welcome.setBackground(new java.awt.Color(0, 193, 255));
        Welcome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome.setText("Welcome + Admin Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        User.setBackground(new java.awt.Color(0, 143, 255));
        User.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User.setText("User Management");
        User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        User.setOpaque(true);
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserMouseExited(evt);
            }
        });

        StockManagement.setBackground(new java.awt.Color(0, 143, 255));
        StockManagement.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        StockManagement.setForeground(new java.awt.Color(255, 255, 255));
        StockManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StockManagement.setText("Stock Management");
        StockManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StockManagement.setOpaque(true);
        StockManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockManagementMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StockManagementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StockManagementMouseExited(evt);
            }
        });

        Price.setBackground(new java.awt.Color(0, 143, 255));
        Price.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Price.setText("Price History");
        Price.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Price.setOpaque(true);
        Price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PriceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PriceMouseExited(evt);
            }
        });

        Approval.setBackground(new java.awt.Color(0, 143, 255));
        Approval.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Approval.setForeground(new java.awt.Color(255, 255, 255));
        Approval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Approval.setText("Approval System");
        Approval.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Approval.setOpaque(true);
        Approval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ApprovalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ApprovalMouseExited(evt);
            }
        });

        Trading.setBackground(new java.awt.Color(0, 143, 255));
        Trading.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Trading.setForeground(new java.awt.Color(255, 255, 255));
        Trading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Trading.setText("Trading Session Control");
        Trading.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Trading.setOpaque(true);
        Trading.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TradingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TradingMouseExited(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 0, 0));
        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainSideLayout = new javax.swing.GroupLayout(MainSide);
        MainSide.setLayout(MainSideLayout);
        MainSideLayout.setHorizontalGroup(
            MainSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainSideLayout.createSequentialGroup()
                .addGroup(MainSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainSideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MainSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Trading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(Approval, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StockManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(MainSideLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(MainSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MainSideLayout.setVerticalGroup(
            MainSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainSideLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Approval, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Trading, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Obj.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(1, 143, 255));

        tfirst.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfirst.setForeground(new java.awt.Color(153, 153, 153));
        tfirst.setText("First Name");
        tfirst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfirstFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfirstFocusLost(evt);
            }
        });

        tlast.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tlast.setForeground(new java.awt.Color(153, 153, 153));
        tlast.setText("Last Name");
        tlast.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tlastFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tlastFocusLost(evt);
            }
        });

        tusername.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tusername.setForeground(new java.awt.Color(153, 153, 153));
        tusername.setText("UserName");
        tusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tusernameFocusLost(evt);
            }
        });

        tpassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tpassword.setForeground(new java.awt.Color(153, 153, 153));
        tpassword.setText("Password");
        tpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tpasswordFocusLost(evt);
            }
        });
        tpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpasswordActionPerformed(evt);
            }
        });

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/Components/add small.png"))); // NOI18N
        button2.setText("Add");
        button2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        button2.setRadius(40);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/Components/rubber.png"))); // NOI18N
        button3.setText("Clear");
        button3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button3.setRadius(40);
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/Components/bin.png"))); // NOI18N
        button4.setText("Remove");
        button4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button4.setRadius(40);
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Username", "E-mail", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(usertable);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Online User : 233,232");

        temail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        temail.setForeground(new java.awt.Color(153, 153, 153));
        temail.setText("ex:username@example.com");
        temail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                temailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                temailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tpassword)
                                .addComponent(tusername)
                                .addComponent(tlast)
                                .addComponent(tfirst, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                .addComponent(temail))
                            .addGap(57, 57, 57)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(tfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tlast, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tpassword))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {temail, tfirst, tlast, tpassword, tusername});

        Obj.addTab("tab7", jPanel10);

        jPanel1.setBackground(new java.awt.Color(0, 143, 255));

        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/Components/add small.png"))); // NOI18N
        button5.setText("Add");
        button5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        button5.setRadius(40);
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/Components/rubber.png"))); // NOI18N
        button6.setText("Clear");
        button6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button6.setRadius(40);
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/Components/bin.png"))); // NOI18N
        button7.setText("Remove");
        button7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button7.setRadius(40);
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        stocktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company", "Quantity", "Initial Price", "Trading Price", "Dividend", "Profit %"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(stocktable);

        tprofit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tprofit.setForeground(new java.awt.Color(153, 153, 153));
        tprofit.setText("Profit Percentage");
        tprofit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tprofitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tprofitFocusLost(evt);
            }
        });
        tprofit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tprofitActionPerformed(evt);
            }
        });

        tdividend.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tdividend.setForeground(new java.awt.Color(153, 153, 153));
        tdividend.setText("Dividend");
        tdividend.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tdividendFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tdividendFocusLost(evt);
            }
        });

        tinitial.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tinitial.setForeground(new java.awt.Color(153, 153, 153));
        tinitial.setText("Initial Price");
        tinitial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tinitialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tinitialFocusLost(evt);
            }
        });

        tquantity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tquantity.setForeground(new java.awt.Color(153, 153, 153));
        tquantity.setText("Available Quantity");
        tquantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tquantityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tquantityFocusLost(evt);
            }
        });

        tcompany.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tcompany.setForeground(new java.awt.Color(153, 153, 153));
        tcompany.setText("Company Name");
        tcompany.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tcompanyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tcompanyFocusLost(evt);
            }
        });

        ttrading.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ttrading.setForeground(new java.awt.Color(153, 153, 153));
        ttrading.setText("Trading Price");
        ttrading.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ttradingFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ttradingFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("$");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("$");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tquantity)
                            .addComponent(tcompany)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tdividend, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tinitial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tprofit, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(ttrading))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tdividend, tinitial, tprofit, ttrading});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tinitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ttrading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tdividend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tprofit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tdividend, tinitial, tprofit, ttrading});

        Obj.addTab("tab6", jPanel1);

        Stocks.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 211, 245));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/Components/financial-profit.png"))); // NOI18N
        jLabel6.setText("Available Stocks");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("242,255");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 211, 245));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/Components/add.png"))); // NOI18N
        jLabel8.setText("Add Stock");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 211, 245));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/Components/remove .png"))); // NOI18N
        jLabel9.setText(" Remove Stock");
        jLabel9.setToolTipText("");
        jLabel9.setAutoscrolls(true);
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jPanel9.setBackground(new java.awt.Color(0, 211, 245));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/Components/add.png"))); // NOI18N
        jLabel10.setText("Order List");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout StocksLayout = new javax.swing.GroupLayout(Stocks);
        Stocks.setLayout(StocksLayout);
        StocksLayout.setHorizontalGroup(
            StocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StocksLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(StocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(StocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        StocksLayout.setVerticalGroup(
            StocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StocksLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(StocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(StocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        Obj.addTab("tab3", Stocks);

        Pricehistory.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout PricehistoryLayout = new javax.swing.GroupLayout(Pricehistory);
        Pricehistory.setLayout(PricehistoryLayout);
        PricehistoryLayout.setHorizontalGroup(
            PricehistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PricehistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );
        PricehistoryLayout.setVerticalGroup(
            PricehistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PricehistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
        );

        Obj.addTab("tab4", Pricehistory);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout ApprovalSysLayout = new javax.swing.GroupLayout(ApprovalSys);
        ApprovalSys.setLayout(ApprovalSysLayout);
        ApprovalSysLayout.setHorizontalGroup(
            ApprovalSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );
        ApprovalSysLayout.setVerticalGroup(
            ApprovalSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApprovalSysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        Obj.addTab("tab5", ApprovalSys);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout TradingSysLayout = new javax.swing.GroupLayout(TradingSys);
        TradingSys.setLayout(TradingSysLayout);
        TradingSysLayout.setHorizontalGroup(
            TradingSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );
        TradingSysLayout.setVerticalGroup(
            TradingSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TradingSysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        Obj.addTab("tab6", TradingSys);

        jLayeredPane1.setLayer(MainSide, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Obj, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(MainSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Obj, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Obj, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 880, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseEntered
                User.setBackground(new Color(0,120,255));
    }//GEN-LAST:event_UserMouseEntered

    private void UserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseExited
                User.setBackground(new Color(0,143,255));
    }//GEN-LAST:event_UserMouseExited

    private void StockManagementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockManagementMouseEntered
                StockManagement.setBackground(new Color(0,120,255));
    }//GEN-LAST:event_StockManagementMouseEntered

    private void StockManagementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockManagementMouseExited
                StockManagement.setBackground(new Color(0,143,255));
    }//GEN-LAST:event_StockManagementMouseExited

    private void PriceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PriceMouseEntered
                Price.setBackground(new Color(0,120,255));
    }//GEN-LAST:event_PriceMouseEntered

    private void PriceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PriceMouseExited
                Price.setBackground(new Color(0,143,255));
    }//GEN-LAST:event_PriceMouseExited

    private void ApprovalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApprovalMouseEntered
                Approval.setBackground(new Color(0,120,255));
    }//GEN-LAST:event_ApprovalMouseEntered

    private void ApprovalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApprovalMouseExited
                Approval.setBackground(new Color(0,143,255));
    }//GEN-LAST:event_ApprovalMouseExited

    private void TradingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TradingMouseEntered
                Trading.setBackground(new Color(0,120,255));
    }//GEN-LAST:event_TradingMouseEntered

    private void TradingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TradingMouseExited
                Trading.setBackground(new Color(0,143,255));
    }//GEN-LAST:event_TradingMouseExited

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
            
            this.dispose();
            new Login().setVisible(true);
            
    }//GEN-LAST:event_LogoutActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
            this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseClicked
        Obj.setSelectedIndex(0);
    }//GEN-LAST:event_UserMouseClicked

    private void StockManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockManagementMouseClicked
        Obj.setSelectedIndex(1);
    }//GEN-LAST:event_StockManagementMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
            new addingStock().setVisible(true);
   
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
            String first = tfirst.getText();
            String last = tlast.getText();
            String username = tusername.getText();
            String password = tpassword.getText();
            String email = temail.getText();

            if(first.isEmpty()||first.equals("First Name") || last.isEmpty()||last.equals("Last Name") || username.isEmpty()||username.equals("UserName") || password.isEmpty()||password.equals("Password")|| email.isEmpty()||email.equals("ex:username@example.com")){
                JOptionPane.showMessageDialog(this, "Please fill all fields !","Try Again", JOptionPane.ERROR_MESSAGE);
            }
            else{
                DefaultTableModel model = (DefaultTableModel) usertable.getModel();
                model.addRow(new Object[]{first+" "+last,username,email,password});
            }
            
            tfirst.setText("First Name");
            tfirst.setForeground(new Color(153,153,153));
            tlast.setText("Last Name");
            tlast.setForeground(new Color(153,153,153));
            tusername.setText("UserName");
            tusername.setForeground(new Color(153,153,153));
            temail.setText("ex:username@example.com");
            temail.setForeground(new Color(153,153,153));
            tpassword.setText("Password");
            tpassword.setForeground(new Color(153,153,153));


    }//GEN-LAST:event_button2ActionPerformed

    private void tpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpasswordActionPerformed

    private void tfirstFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfirstFocusGained
            if(tfirst.getText().equals("First Name")){
                tfirst.setText("");
                tfirst.setForeground(Color.BLACK);
            }
    }//GEN-LAST:event_tfirstFocusGained

    private void tfirstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfirstFocusLost
                if(tfirst.getText().equals("")){
                tfirst.setText("First Name");
                tfirst.setForeground(new Color(153,153,153));
            }    }//GEN-LAST:event_tfirstFocusLost

    private void tlastFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tlastFocusGained
             if(tlast.getText().equals("Last Name")){
                tlast.setText("");
                tlast.setForeground(Color.BLACK);
            }
    }//GEN-LAST:event_tlastFocusGained

    private void tlastFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tlastFocusLost
             if(tlast.getText().equals("")){
                tlast.setText("Last Name");
                tlast.setForeground(new Color(153,153,153));
            }    
    }//GEN-LAST:event_tlastFocusLost

    private void tusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tusernameFocusGained
            if(tusername.getText().equals("UserName")){
                tusername.setText("");
                tusername.setForeground(Color.BLACK);
            }    }//GEN-LAST:event_tusernameFocusGained

    private void tusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tusernameFocusLost
if(tusername.getText().equals("UserName")){
                tlast.setText("");
                tlast.setForeground(new Color(153,153,153));
            }    }//GEN-LAST:event_tusernameFocusLost

    private void temailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temailFocusGained
            if(temail.getText().equals("ex:username@example.com")){
                temail.setText("");
                temail.setForeground(Color.BLACK);
            }
    }//GEN-LAST:event_temailFocusGained

    private void temailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temailFocusLost
if(temail.getText().equals("")){
                temail.setText("ex:username@example.com");
                temail.setForeground(new Color(153,153,153));
            }    }//GEN-LAST:event_temailFocusLost

    private void tpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpasswordFocusGained
        if(tpassword.getText().equals("Password")){
                tpassword.setText("");
                tpassword.setForeground(Color.BLACK);
            }
    }//GEN-LAST:event_tpasswordFocusGained

    private void tpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpasswordFocusLost
        if(tpassword.getText().equals("")){
                tpassword.setText("Password");
                tpassword.setForeground(new Color(153,153,153));
            }
    }//GEN-LAST:event_tpasswordFocusLost

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
            int row = usertable.getSelectedRow();
            
            if(row<0){
                JOptionPane.showMessageDialog(this,"No row is selected! Please select a row","Please Select One",JOptionPane.ERROR_MESSAGE);
                
            }else{
                DefaultTableModel model = (DefaultTableModel) usertable.getModel();
                model.removeRow(row);
            }
    }//GEN-LAST:event_button4ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
            tfirst.setText("First Name");
            tfirst.setForeground(new Color(153,153,153));
            tlast.setText("Last Name");
            tlast.setForeground(new Color(153,153,153));
            tusername.setText("UserName");
            tusername.setForeground(new Color(153,153,153));
            temail.setText("ex:username@example.com");
            temail.setForeground(new Color(153,153,153));
            tpassword.setText("Password");
            tpassword.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_button3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
DefaultTableModel model = (DefaultTableModel) usertable.getModel();
        Vector<Vector> tableData = model.getDataVector();
        
        //Saving of object in a file
        try {
            FileOutputStream file = new FileOutputStream("file.bin");
            ObjectOutputStream output = new ObjectOutputStream(file);
            
            // Method for serialization of object
            output.writeObject(tableData);

            output.close();
            file.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            FileInputStream file = new FileInputStream("file.bin");
            ObjectInputStream input = new ObjectInputStream(file);
            // Method for deserialization of object
            Vector<Vector> tableData = (Vector<Vector>)input.readObject();
            
            input.close();
            file.close();
            
            
            DefaultTableModel model = (DefaultTableModel) usertable.getModel();
            for (int i = 0; i < tableData.size(); i++) {
                Vector row = tableData.get(i);
                model.addRow(new Object[]{row.get(0), row.get(1), row.get(2), row.get(3)});
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
            String company = tcompany.getText();
            String quantity = tquantity.getText();
            String initial = tinitial.getText();
            String trading = ttrading.getText();
            String dividend = tdividend.getText();
            String profit = tprofit.getText();

            if(company.isEmpty()||company.equals("Company Name") || quantity.isEmpty()||quantity.equals("Available Quantity") || initial.isEmpty()||initial.equals("Initial Price") || trading.isEmpty()||trading.equals("Trading Price")|| dividend.isEmpty()||dividend.equals("Dividend")||profit.isEmpty()||profit.equals("Profit Percentage")){
                JOptionPane.showMessageDialog(this, "Please fill all fields !","Try Again", JOptionPane.ERROR_MESSAGE);
            }
            else{
                DefaultTableModel model = (DefaultTableModel) stocktable.getModel();
                model.addRow(new Object[]{company,quantity,initial,trading,dividend,profit});
            }
            
            tcompany.setText("Company Name");
            tcompany.setForeground(new Color(153,153,153));
            tquantity.setText("Available Quantity");
            tquantity.setForeground(new Color(153,153,153));
            tinitial.setText("Initial Price");
            tinitial.setForeground(new Color(153,153,153));
            ttrading.setText("Trading Price");
            ttrading.setForeground(new Color(153,153,153));
            tdividend.setText("Dividend");
            tdividend.setForeground(new Color(153,153,153));
            tprofit.setText("Profit Percentage");
            tprofit.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
            tcompany.setText("Company Name");
            tcompany.setForeground(new Color(153,153,153));
            tquantity.setText("Available Quantity");
            tquantity.setForeground(new Color(153,153,153));
            tinitial.setText("Initial Price");
            tinitial.setForeground(new Color(153,153,153));
            ttrading.setText("Trading Price");
            ttrading.setForeground(new Color(153,153,153));
            tdividend.setText("Dividend");
            tdividend.setForeground(new Color(153,153,153));
            tprofit.setText("Profit Percentage");
            tprofit.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
                int row = usertable.getSelectedRow();
            
            if(row<0){
                JOptionPane.showMessageDialog(this,"No row is selected! Please select a row","Please Select One",JOptionPane.ERROR_MESSAGE);
                
            }else{
                DefaultTableModel model = (DefaultTableModel) stocktable.getModel();
                model.removeRow(row);
            }
    }//GEN-LAST:event_button7ActionPerformed

    private void tprofitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tprofitFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tprofitFocusGained

    private void tprofitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tprofitFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tprofitFocusLost

    private void tprofitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tprofitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tprofitActionPerformed

    private void tdividendFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tdividendFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tdividendFocusGained

    private void tdividendFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tdividendFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tdividendFocusLost

    private void tinitialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tinitialFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tinitialFocusGained

    private void tinitialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tinitialFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tinitialFocusLost

    private void tquantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tquantityFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tquantityFocusGained

    private void tquantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tquantityFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tquantityFocusLost

    private void tcompanyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tcompanyFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tcompanyFocusGained

    private void tcompanyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tcompanyFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tcompanyFocusLost

    private void ttradingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ttradingFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ttradingFocusGained

    private void ttradingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ttradingFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ttradingFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);

                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Approval;
    private javax.swing.JPanel ApprovalSys;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel MainSide;
    private javax.swing.JTabbedPane Obj;
    private javax.swing.JLabel Price;
    private javax.swing.JPanel Pricehistory;
    private javax.swing.JLabel StockManagement;
    private javax.swing.JPanel Stocks;
    private javax.swing.JLabel Trading;
    private javax.swing.JPanel TradingSys;
    private javax.swing.JLabel User;
    private javax.swing.JLabel Welcome;
    private frontend.start.Button button2;
    private frontend.start.Button button3;
    private frontend.start.Button button4;
    private frontend.start.Button button5;
    private frontend.start.Button button6;
    private frontend.start.Button button7;
    private frontend.Components.Clock clock1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable stocktable;
    private javax.swing.JTextField tcompany;
    private javax.swing.JTextField tdividend;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tfirst;
    private javax.swing.JTextField tinitial;
    private javax.swing.JTextField tlast;
    private javax.swing.JTextField tpassword;
    private javax.swing.JTextField tprofit;
    private javax.swing.JTextField tquantity;
    private javax.swing.JTextField ttrading;
    private javax.swing.JTextField tusername;
    private javax.swing.JTable usertable;
    // End of variables declaration//GEN-END:variables
}
