package frontend.start;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import backend.UsersDatabase;
import backend.User;
import java.util.Map;

/**
 *
 * @author Hagras
 */
public class Admin extends javax.swing.JFrame {
    
    UsersDatabase usersDatabase = UsersDatabase.getInstance();
    Map<String, backend.User> users = usersDatabase.getUsersHashmap();

    public Admin() {
        setUndecorated(true);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        MainSide = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        StockManagement = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        Approval = new javax.swing.JLabel();
        Trading = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Obj = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        tfirst = new javax.swing.JTextField();
        tlast = new javax.swing.JTextField();
        tusername = new javax.swing.JTextField();
        tpassword = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        Addbtn = new frontend.start.Button();
        Clearbtn = new frontend.start.Button();
        Removebtn = new frontend.start.Button();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        stocktable = new javax.swing.JTable();
        tprofit = new javax.swing.JTextField();
        tdividend = new javax.swing.JTextField();
        tinitial = new javax.swing.JTextField();
        tquantity = new javax.swing.JTextField();
        tcompany = new javax.swing.JTextField();
        ttrading = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Pricehistory = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        ApprovalSys = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        TradingSys = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setBackground(new java.awt.Color(255, 255, 255));
        /**addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened();
            }
        });**/
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));

        MainSide.setBackground(new java.awt.Color(0, 143, 255));

        jPanel3.setBackground(new java.awt.Color(0, 118, 255));

        Welcome.setBackground(new java.awt.Color(0, 193, 255));
        Welcome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome.setText("Welcome + Admin Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        User.setBackground(new java.awt.Color(0, 143, 255));
        User.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User.setText("User Management");
        User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        User.setOpaque(true);
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserMouseExited(evt);
            }
        });

        StockManagement.setBackground(new java.awt.Color(0, 143, 255));
        StockManagement.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        StockManagement.setForeground(new java.awt.Color(255, 255, 255));
        StockManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StockManagement.setText("Stock Management");
        StockManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StockManagement.setOpaque(true);
        StockManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockManagementMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StockManagementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StockManagementMouseExited(evt);
            }
        });

        Price.setBackground(new java.awt.Color(0, 143, 255));
        Price.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Price.setText("Price History");
        Price.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Price.setOpaque(true);
        Price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PriceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PriceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PriceMouseExited(evt);
            }
        });

        Approval.setBackground(new java.awt.Color(0, 143, 255));
        Approval.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Approval.setForeground(new java.awt.Color(255, 255, 255));
        Approval.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Approval.setText("Approval System");
        Approval.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Approval.setOpaque(true);
        Approval.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApprovalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ApprovalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ApprovalMouseExited(evt);
            }
        });

        Trading.setBackground(new java.awt.Color(0, 143, 255));
        Trading.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Trading.setForeground(new java.awt.Color(255, 255, 255));
        Trading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Trading.setText("Trading Session Control");
        Trading.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Trading.setOpaque(true);
        Trading.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TradingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TradingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TradingMouseExited(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 0, 0));
        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainSideLayout = new javax.swing.GroupLayout(MainSide);
        MainSide.setLayout(MainSideLayout);
        MainSideLayout.setHorizontalGroup(
            MainSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainSideLayout.createSequentialGroup()
                .addGroup(MainSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainSideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MainSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Trading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(Approval, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StockManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(MainSideLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(MainSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MainSideLayout.setVerticalGroup(
            MainSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainSideLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Approval, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Trading, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Obj.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(1, 143, 255));

        tfirst.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfirst.setForeground(new java.awt.Color(153, 153, 153));
        tfirst.setText("First Name");
        tfirst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfirstFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfirstFocusLost(evt);
            }
        });
        tfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfirstActionPerformed(evt);
            }
        });

        tlast.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tlast.setForeground(new java.awt.Color(153, 153, 153));
        tlast.setText("Last Name");
        tlast.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tlastFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tlastFocusLost(evt);
            }
        });

        tusername.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tusername.setForeground(new java.awt.Color(153, 153, 153));
        tusername.setText("UserName");
        tusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tusernameFocusLost(evt);
            }
        });

        tpassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tpassword.setForeground(new java.awt.Color(153, 153, 153));
        tpassword.setText("Password");
        tpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tpasswordFocusLost(evt);
            }
        });
        tpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpasswordActionPerformed(evt);
            }
        });

        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Username", "E-mail", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(usertable);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Online User : 233,232");

        temail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        temail.setForeground(new java.awt.Color(153, 153, 153));
        temail.setText("ex:username@example.com");
        temail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                temailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                temailFocusLost(evt);
            }
        });

        Addbtn.setText("Add");
        Addbtn.setRadius(50);
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        Clearbtn.setText("Clear");
        Clearbtn.setRadius(50);
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });

        Removebtn.setText("Remove");
        Removebtn.setRadius(50);
        Removebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovebtnActionPerformed(evt);
            }
        });

       // jCheckBox1.setText("admin");
        /**CheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });**/

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tpassword)
                            .addComponent(tusername)
                            .addComponent(tlast)
                            .addComponent(tfirst, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(temail))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Removebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Addbtn, Clearbtn, Removebtn});

        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(tfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tlast, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tpassword))
                    .addComponent(Removebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {temail, tfirst, tlast, tpassword, tusername});

        jPanel10Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Addbtn, Clearbtn, Removebtn});

        Obj.addTab("tab7", jPanel10);

        jPanel1.setBackground(new java.awt.Color(0, 143, 255));

        stocktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company", "Quantity", "Initial Price", "Trading Price", "Dividend", "Profit %"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(stocktable);

        tprofit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tprofit.setForeground(new java.awt.Color(153, 153, 153));
        tprofit.setText("Profit Percentage");
        tprofit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tprofitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tprofitFocusLost(evt);
            }
        });
        tprofit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tprofitActionPerformed(evt);
            }
        });

        tdividend.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tdividend.setForeground(new java.awt.Color(153, 153, 153));
        tdividend.setText("Dividend");
        tdividend.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tdividendFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tdividendFocusLost(evt);
            }
        });

        tinitial.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tinitial.setForeground(new java.awt.Color(153, 153, 153));
        tinitial.setText("Initial Price");
        tinitial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tinitialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tinitialFocusLost(evt);
            }
        });

        tquantity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tquantity.setForeground(new java.awt.Color(153, 153, 153));
        tquantity.setText("Available Quantity");
        tquantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tquantityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tquantityFocusLost(evt);
            }
        });

        tcompany.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tcompany.setForeground(new java.awt.Color(153, 153, 153));
        tcompany.setText("Company Name");
        tcompany.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tcompanyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tcompanyFocusLost(evt);
            }
        });

        ttrading.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ttrading.setForeground(new java.awt.Color(153, 153, 153));
        ttrading.setText("Trading Price");
        ttrading.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ttradingFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ttradingFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("$");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("$");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tquantity)
                            .addComponent(tcompany)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tdividend, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tinitial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tprofit, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(ttrading))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tdividend, tinitial, tprofit, ttrading});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(tcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tinitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ttrading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tdividend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tprofit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tdividend, tinitial, tprofit, ttrading});

        Obj.addTab("tab6", jPanel1);

        Pricehistory.setBackground(new java.awt.Color(0, 143, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Price History");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable5);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Order List");

        javax.swing.GroupLayout PricehistoryLayout = new javax.swing.GroupLayout(Pricehistory);
        Pricehistory.setLayout(PricehistoryLayout);
        PricehistoryLayout.setHorizontalGroup(
            PricehistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PricehistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PricehistoryLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(PricehistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PricehistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PricehistoryLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        PricehistoryLayout.setVerticalGroup(
            PricehistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PricehistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PricehistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PricehistoryLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(304, Short.MAX_VALUE)))
        );

        Obj.addTab("tab4", Pricehistory);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout ApprovalSysLayout = new javax.swing.GroupLayout(ApprovalSys);
        ApprovalSys.setLayout(ApprovalSysLayout);
        ApprovalSysLayout.setHorizontalGroup(
            ApprovalSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );
        ApprovalSysLayout.setVerticalGroup(
            ApprovalSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApprovalSysLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        Obj.addTab("tab5", ApprovalSys);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout TradingSysLayout = new javax.swing.GroupLayout(TradingSys);
        TradingSys.setLayout(TradingSysLayout);
        TradingSysLayout.setHorizontalGroup(
            TradingSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );
        TradingSysLayout.setVerticalGroup(
            TradingSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TradingSysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        Obj.addTab("tab6", TradingSys);

        jLayeredPane1.setLayer(MainSide, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Obj, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(MainSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Obj, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Obj, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 880, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void UserMouseEntered(java.awt.event.MouseEvent evt) {                                  
        User.setBackground(new Color(0, 120, 255));

    }                                 

    private void UserMouseExited(java.awt.event.MouseEvent evt) {                                 
        User.setBackground(new Color(0, 143, 255));
    }                                

    private void StockManagementMouseEntered(java.awt.event.MouseEvent evt) {                                             
        StockManagement.setBackground(new Color(0, 120, 255));
    }                                            

    private void StockManagementMouseExited(java.awt.event.MouseEvent evt) {                                            
        StockManagement.setBackground(new Color(0, 143, 255));
    }                                           

    private void PriceMouseEntered(java.awt.event.MouseEvent evt) {                                   
        Price.setBackground(new Color(0, 120, 255));
    }                                  

    private void PriceMouseExited(java.awt.event.MouseEvent evt) {                                  
        Price.setBackground(new Color(0, 143, 255));
    }                                 

    private void ApprovalMouseEntered(java.awt.event.MouseEvent evt) {                                      
        Approval.setBackground(new Color(0, 120, 255));
    }                                     

    private void ApprovalMouseExited(java.awt.event.MouseEvent evt) {                                     
        Approval.setBackground(new Color(0, 143, 255));
    }                                    

    private void TradingMouseEntered(java.awt.event.MouseEvent evt) {                                     
        Trading.setBackground(new Color(0, 120, 255));
    }                                    

    private void TradingMouseExited(java.awt.event.MouseEvent evt) {                                    
        Trading.setBackground(new Color(0, 143, 255));
    }                                   

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {                                       

        this.dispose();
        new Login().setVisible(true);

    }                                      

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {                                     
        this.dispose();
    }                                    

    private void UserMouseClicked(java.awt.event.MouseEvent evt) {                                  
        Obj.setSelectedIndex(0);
    }                                 

    private void StockManagementMouseClicked(java.awt.event.MouseEvent evt) {                                             
        Obj.setSelectedIndex(1);
    }                                            

    

    private void tpasswordActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void tfirstFocusGained(java.awt.event.FocusEvent evt) {                                   
        if (tfirst.getText().equals("First Name")) {
            tfirst.setText("");
            tfirst.setForeground(Color.BLACK);
        }
    }                                  

    private void tfirstFocusLost(java.awt.event.FocusEvent evt) {                                 
        if (tfirst.getText().equals("")) {
            tfirst.setText("First Name");
            tfirst.setForeground(new Color(153, 153, 153));
            }    }                                

    private void tlastFocusGained(java.awt.event.FocusEvent evt) {                                  
        if (tlast.getText().equals("Last Name")) {
            tlast.setText("");
            tlast.setForeground(Color.BLACK);
        }
    }                                 

    private void tlastFocusLost(java.awt.event.FocusEvent evt) {                                
        if (tlast.getText().equals("")) {
            tlast.setText("Last Name");
            tlast.setForeground(new Color(153, 153, 153));
        }
    }                               

    private void tusernameFocusGained(java.awt.event.FocusEvent evt) {                                      
        if (tusername.getText().equals("UserName")) {
            tusername.setText("");
            tusername.setForeground(Color.BLACK);
            }    }                                     

    private void tusernameFocusLost(java.awt.event.FocusEvent evt) {                                    
        if (tusername.getText().equals("UserName")) {
            tlast.setText("");
            tlast.setForeground(new Color(153, 153, 153));
            }    }                                   

    private void temailFocusGained(java.awt.event.FocusEvent evt) {                                   
        if (temail.getText().equals("ex:username@example.com")) {
            temail.setText("");
            temail.setForeground(Color.BLACK);
        }
    }                                  

    private void temailFocusLost(java.awt.event.FocusEvent evt) {                                 
        if (temail.getText().equals("")) {
            temail.setText("ex:username@example.com");
            temail.setForeground(new Color(153, 153, 153));
            }    }                                

    private void tpasswordFocusGained(java.awt.event.FocusEvent evt) {                                      
        if (tpassword.getText().equals("Password")) {
            tpassword.setText("");
            tpassword.setForeground(Color.BLACK);
        }
    }                                     

    private void tpasswordFocusLost(java.awt.event.FocusEvent evt) {                                    
        if (tpassword.getText().equals("")) {
            tpassword.setText("Password");
            tpassword.setForeground(new Color(153, 153, 153));
        }
    }                                   

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int row = usertable.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(this, "No row is selected! Please select a row", "Please Select One", JOptionPane.ERROR_MESSAGE);

        } else {
            DefaultTableModel model = (DefaultTableModel) usertable.getModel();
            model.removeRow(row);
        }
    }                                       

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        tfirst.setText("First Name");
        tfirst.setForeground(new Color(153, 153, 153));
        tlast.setText("Last Name");
        tlast.setForeground(new Color(153, 153, 153));
        tusername.setText("UserName");
        tusername.setForeground(new Color(153, 153, 153));
        temail.setText("ex:username@example.com");
        temail.setForeground(new Color(153, 153, 153));
        tpassword.setText("Password");
        tpassword.setForeground(new Color(153, 153, 153));
    }                                       

    private void formWindowOpened() {                                  

        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) usertable.getModel();

        for (User user : users.values()) {
            String username = user.getUsername();
            String password = user.getPassword();
            String admin = user.getClass().getSimpleName().equals("Admin")?"admin":"regular user";
            model.addRow(new Object[]{0, username, admin, password});
        }


    }                                 

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String company = tcompany.getText();
        String quantity = tquantity.getText();
        String initial = tinitial.getText();
        String trading = ttrading.getText();
        String dividend = tdividend.getText();
        String profit = tprofit.getText();

        if (company.isEmpty() || company.equals("Company Name") || quantity.isEmpty() || quantity.equals("Available Quantity") || initial.isEmpty() || initial.equals("Initial Price") || trading.isEmpty() || trading.equals("Trading Price") || dividend.isEmpty() || dividend.equals("Dividend") || profit.isEmpty() || profit.equals("Profit Percentage")) {
            JOptionPane.showMessageDialog(this, "Please fill all fields !", "Try Again", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) stocktable.getModel();
            model.addRow(new Object[]{company, quantity, initial, trading, dividend, profit});
        }

        tcompany.setText("Company Name");
        tcompany.setForeground(new Color(153, 153, 153));
        tquantity.setText("Available Quantity");
        tquantity.setForeground(new Color(153, 153, 153));
        tinitial.setText("Initial Price");
        tinitial.setForeground(new Color(153, 153, 153));
        ttrading.setText("Trading Price");
        ttrading.setForeground(new Color(153, 153, 153));
        tdividend.setText("Dividend");
        tdividend.setForeground(new Color(153, 153, 153));
        tprofit.setText("Profit Percentage");
        tprofit.setForeground(new Color(153, 153, 153));
    }                                       

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        tcompany.setText("Company Name");
        tcompany.setForeground(new Color(153, 153, 153));
        tquantity.setText("Available Quantity");
        tquantity.setForeground(new Color(153, 153, 153));
        tinitial.setText("Initial Price");
        tinitial.setForeground(new Color(153, 153, 153));
        ttrading.setText("Trading Price");
        ttrading.setForeground(new Color(153, 153, 153));
        tdividend.setText("Dividend");
        tdividend.setForeground(new Color(153, 153, 153));
        tprofit.setText("Profit Percentage");
        tprofit.setForeground(new Color(153, 153, 153));
    }                                       

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int row = stocktable.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(this, "No row is selected! Please select a row", "Please Select One", JOptionPane.ERROR_MESSAGE);

        } else {
            DefaultTableModel model = (DefaultTableModel) stocktable.getModel();
            model.removeRow(row);
        }
    }                                       

    private void tprofitFocusGained(java.awt.event.FocusEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void tprofitFocusLost(java.awt.event.FocusEvent evt) {                                  
        // TODO add your handling code here:
    }                                 

    private void tprofitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void tdividendFocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void tdividendFocusLost(java.awt.event.FocusEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void tinitialFocusGained(java.awt.event.FocusEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void tinitialFocusLost(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void tquantityFocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void tquantityFocusLost(java.awt.event.FocusEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void tcompanyFocusGained(java.awt.event.FocusEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void tcompanyFocusLost(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void ttradingFocusGained(java.awt.event.FocusEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void ttradingFocusLost(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void PriceMouseClicked(java.awt.event.MouseEvent evt) {                                   
        Obj.setSelectedIndex(2);
    }                                  

    private void ApprovalMouseClicked(java.awt.event.MouseEvent evt) {                                      
        Obj.setSelectedIndex(3);
    }                                     

    private void TradingMouseClicked(java.awt.event.MouseEvent evt) {                                     
        Obj.setSelectedIndex(4);
    }                                    

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        String first = tfirst.getText();
        String last = tlast.getText();
        String username = tusername.getText();
        String password = tpassword.getText();
        String admin = temail.getText();

        if (first.isEmpty() || first.equals("First Name") || last.isEmpty() || last.equals("Last Name") || username.isEmpty() || username.equals("UserName") || password.isEmpty() || password.equals("Password") || admin.isEmpty() || admin.equals("ex:username@example.com")) {
            JOptionPane.showMessageDialog(this, "Please fill all fields !", "Try Again", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) usertable.getModel();
            boolean isadmin = admin.equals("admin");
            usersDatabase.register(username, password, isadmin);
            formWindowOpened();

        }

        tfirst.setText("First Name");
        tfirst.setForeground(new Color(153, 153, 153));
        tlast.setText("Last Name");
        tlast.setForeground(new Color(153, 153, 153));
        tusername.setText("UserName");
        tusername.setForeground(new Color(153, 153, 153));
        temail.setText("ex:username@example.com");
        temail.setForeground(new Color(153, 153, 153));
        tpassword.setText("Password");
        tpassword.setForeground(new Color(153, 153, 153));    }                                      

    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        tfirst.setText("First Name");
        tfirst.setForeground(new Color(153, 153, 153));
        tlast.setText("Last Name");
        tlast.setForeground(new Color(153, 153, 153));
        tusername.setText("UserName");
        tusername.setForeground(new Color(153, 153, 153));
        temail.setText("ex:username@example.com");
        temail.setForeground(new Color(153, 153, 153));
        tpassword.setText("Password");
        tpassword.setForeground(new Color(153, 153, 153));    }                                        

    private void RemovebtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int row = usertable.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(this, "No row is selected! Please select a row", "Please Select One", JOptionPane.ERROR_MESSAGE);

        } else {
            DefaultTableModel model = (DefaultTableModel) usertable.getModel();
            model.removeRow(row);
        }    }                                         

    private void tfirstActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      
                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);

            }

        });
    }

    // Variables declaration - do not modify                     
    private frontend.start.Button Addbtn;
    private javax.swing.JLabel Approval;
    private javax.swing.JPanel ApprovalSys;
    private frontend.start.Button Clearbtn;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel MainSide;
    private javax.swing.JTabbedPane Obj;
    private javax.swing.JLabel Price;
    private javax.swing.JPanel Pricehistory;
    private frontend.start.Button Removebtn;
    private javax.swing.JLabel StockManagement;
    private javax.swing.JLabel Trading;
    private javax.swing.JPanel TradingSys;
    private javax.swing.JLabel User;
    private javax.swing.JLabel Welcome;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable stocktable;
    private javax.swing.JTextField tcompany;
    private javax.swing.JTextField tdividend;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tfirst;
    private javax.swing.JTextField tinitial;
    private javax.swing.JTextField tlast;
    private javax.swing.JTextField tpassword;
    private javax.swing.JTextField tprofit;
    private javax.swing.JTextField tquantity;
    private javax.swing.JTextField ttrading;
    private javax.swing.JTextField tusername;
    private javax.swing.JTable usertable;
    // End of variables declaration                   
}
